#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# load homebrew installed completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# iTerm2 integration
if [ "$TERM_PROGRAM" = "iTerm.app" ]; then
    export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=YES
    source ~/.iterm2_shell_integration.zsh
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# additional keybindings
bindkey $terminfo[kpp] history-beginning-search-backward
bindkey $terminfo[knp] history-beginning-search-forward

# some more aliases
alias cal='cal -m'
alias 3m='cal -m3'
alias year='cal -my'

# for compatibility reasons
alias p='lsarchive'
alias x='unarchive'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
